# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "GoCardless CLI"
  homepage "https://github.com/gocardless/cli-releases"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gocardless/cli-releases/releases/download/v1.0.2/cli_1.0.2_macOS_x86_64.tar.gz"
      sha256 "0708eb79da1cd79741e43766ac11b44298d9d64e29cf81a8fe3b999ede43e234"

      def install
        bin.install "gc"
        bin.install_symlink "gc" => "gocardless"

        # Install shell auto-completion
        (bash_completion/"gc").write(Utils.popen_read("#{bin}/gc completion bash"))
        (zsh_completion/"_gc").write(Utils.popen_read("#{bin}/gc completion zsh"))
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gocardless/cli-releases/releases/download/v1.0.2/cli_1.0.2_Linux_arm64.tar.gz"
      sha256 "a9e58069ad306e950edbbcda733e31a3c49dead5bb45d4f1e4b06d551ddf8cac"

      def install
        bin.install "gc"
        bin.install_symlink "gc" => "gocardless"

        # Install shell auto-completion
        (bash_completion/"gc").write(Utils.popen_read("#{bin}/gc completion bash"))
        (zsh_completion/"_gc").write(Utils.popen_read("#{bin}/gc completion zsh"))
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gocardless/cli-releases/releases/download/v1.0.2/cli_1.0.2_Linux_x86_64.tar.gz"
      sha256 "afd76e41c0690beea7fea19470e199553caa220869a88d3b5c4c48958684d97b"

      def install
        bin.install "gc"
        bin.install_symlink "gc" => "gocardless"

        # Install shell auto-completion
        (bash_completion/"gc").write(Utils.popen_read("#{bin}/gc completion bash"))
        (zsh_completion/"_gc").write(Utils.popen_read("#{bin}/gc completion zsh"))
      end
    end
  end

  test do
    system "#{bin}/gc version"
  end
end
