# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "GoCardless CLI"
  homepage "https://github.com/gocardless/cli-releases"
  version "1.0.0-alpha.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gocardless/cli-releases/releases/download/v1.0.0-alpha.3/cli_1.0.0-alpha.3_masOS_arm64.tar.gz"
      sha256 "0798ddde24e24158de999f2fb054d639730caee8619368a940cb62f6e73cfd06"

      def install
        bin.install "gc"
        bin.install_symlink "gc" => "gocardless"

        # Install shell auto-completion
        (bash_completion/"gc").write(Utils.popen_read("#{bin}/gc completion bash"))
        (zsh_completion/"_gc").write(Utils.popen_read("#{bin}/gc completion zsh"))
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gocardless/cli-releases/releases/download/v1.0.0-alpha.3/cli_1.0.0-alpha.3_masOS_x86_64.tar.gz"
      sha256 "b61978979c1b110174ace13bae62e1b0d7e1e87ea2017f5809a35de6e2f4f758"

      def install
        bin.install "gc"
        bin.install_symlink "gc" => "gocardless"

        # Install shell auto-completion
        (bash_completion/"gc").write(Utils.popen_read("#{bin}/gc completion bash"))
        (zsh_completion/"_gc").write(Utils.popen_read("#{bin}/gc completion zsh"))
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gocardless/cli-releases/releases/download/v1.0.0-alpha.3/cli_1.0.0-alpha.3_Linux_arm64.tar.gz"
      sha256 "f51c62307778d6d9e94bab20936516b0d4472759f562c98e48326a8b6796dc5d"

      def install
        bin.install "gc"
        bin.install_symlink "gc" => "gocardless"

        # Install shell auto-completion
        (bash_completion/"gc").write(Utils.popen_read("#{bin}/gc completion bash"))
        (zsh_completion/"_gc").write(Utils.popen_read("#{bin}/gc completion zsh"))
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gocardless/cli-releases/releases/download/v1.0.0-alpha.3/cli_1.0.0-alpha.3_Linux_x86_64.tar.gz"
      sha256 "008f0b03fa502088113810fafa1639f101f061872c089e07dfb17881c8303a96"

      def install
        bin.install "gc"
        bin.install_symlink "gc" => "gocardless"

        # Install shell auto-completion
        (bash_completion/"gc").write(Utils.popen_read("#{bin}/gc completion bash"))
        (zsh_completion/"_gc").write(Utils.popen_read("#{bin}/gc completion zsh"))
      end
    end
  end

  test do
    system "#{bin}/gc version"
  end
end
