# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "GoCardless CLI"
  homepage "https://github.com/gocardless/cli-releases"
  version "1.0.0-beta.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gocardless/cli-releases/releases/download/v1.0.0-beta.2/cli_1.0.0-beta.2_macOS_arm64.tar.gz"
      sha256 "d349aef2a6a2b94b2f4d9cacee5b0e00826874ef8aa273ad87d94cf2a9b37467"

      def install
        bin.install "gc"
        bin.install_symlink "gc" => "gocardless"

        # Install shell auto-completion
        (bash_completion/"gc").write(Utils.popen_read("#{bin}/gc completion bash"))
        (zsh_completion/"_gc").write(Utils.popen_read("#{bin}/gc completion zsh"))
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gocardless/cli-releases/releases/download/v1.0.0-beta.2/cli_1.0.0-beta.2_macOS_x86_64.tar.gz"
      sha256 "485c310564a8cf8f46de82eeb982370d95ec767c8d10335fc10172bc4450b2fc"

      def install
        bin.install "gc"
        bin.install_symlink "gc" => "gocardless"

        # Install shell auto-completion
        (bash_completion/"gc").write(Utils.popen_read("#{bin}/gc completion bash"))
        (zsh_completion/"_gc").write(Utils.popen_read("#{bin}/gc completion zsh"))
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gocardless/cli-releases/releases/download/v1.0.0-beta.2/cli_1.0.0-beta.2_Linux_arm64.tar.gz"
      sha256 "98c24eadb6d46077b14f5f3f987e9b9a8a16604ae709ec235242125c81ff0f82"

      def install
        bin.install "gc"
        bin.install_symlink "gc" => "gocardless"

        # Install shell auto-completion
        (bash_completion/"gc").write(Utils.popen_read("#{bin}/gc completion bash"))
        (zsh_completion/"_gc").write(Utils.popen_read("#{bin}/gc completion zsh"))
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gocardless/cli-releases/releases/download/v1.0.0-beta.2/cli_1.0.0-beta.2_Linux_x86_64.tar.gz"
      sha256 "6df9f0e9d73a42f765161d1200e158d84291fb6f2d2c7ae2b21a659fcc174fcb"

      def install
        bin.install "gc"
        bin.install_symlink "gc" => "gocardless"

        # Install shell auto-completion
        (bash_completion/"gc").write(Utils.popen_read("#{bin}/gc completion bash"))
        (zsh_completion/"_gc").write(Utils.popen_read("#{bin}/gc completion zsh"))
      end
    end
  end

  test do
    system "#{bin}/gc version"
  end
end
