# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crank < Formula
  desc "GoCardless JSONSchema template generator"
  homepage "https://github.com/gocardless/crank"
  version "6.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gocardless/crank/releases/download/v6.0.0/crank_6.0.0_macOS_x86_64.tar.gz"
      sha256 "e30963588d7c5ded6fe648dcf2296cfbfc8cbb7dd011b72a2dc97a368e11883f"

      def install
        bin.install "crank"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gocardless/crank/releases/download/v6.0.0/crank_6.0.0_macOS_arm64.tar.gz"
      sha256 "f991cfd49837e687ca6056a261a1c2485b0ff87be385458f39c3803470a782f4"

      def install
        bin.install "crank"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gocardless/crank/releases/download/v6.0.0/crank_6.0.0_Linux_x86_64.tar.gz"
        sha256 "9f999d103ef9ae762f81de26173b6703300433c2ec1b0dc57d282766d4eb52cc"

        def install
          bin.install "crank"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gocardless/crank/releases/download/v6.0.0/crank_6.0.0_Linux_arm64.tar.gz"
        sha256 "7438e0c4b12ddd8f63871449d19863feba9659c58646ef81e2e5fd845af079e7"

        def install
          bin.install "crank"
        end
      end
    end
  end

  test do
    system "#{bin}/crank"
  end
end
