# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/gc/github_private_release_download_strategy"
class Crank < Formula
  desc "GoCardless JSONSchema template generator"
  homepage "https://github.com/gocardless/crank"
  version "6.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gocardless/crank/releases/download/v6.0.0/crank_6.0.0_macOS_x86_64.tar.gz", using: Gc::GithubPrivateReleaseDownloadStrategy
      sha256 "5cd295b4bf7b29b97b8cba6709827b90ffedf2e9b50577a499f04a92f366bc26"

      def install
        bin.install "crank"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gocardless/crank/releases/download/v6.0.0/crank_6.0.0_macOS_arm64.tar.gz", using: Gc::GithubPrivateReleaseDownloadStrategy
      sha256 "4ce80f3b8d60ee74dc1a0a0746bec4bd00dc7777015166ecee4ebfe4e43b756a"

      def install
        bin.install "crank"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gocardless/crank/releases/download/v6.0.0/crank_6.0.0_Linux_x86_64.tar.gz", using: Gc::GithubPrivateReleaseDownloadStrategy
        sha256 "e68f8db7f49137b6b7cd73c7fd421040dbaee2b3cbb854bc686bf724bcab8473"

        def install
          bin.install "crank"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gocardless/crank/releases/download/v6.0.0/crank_6.0.0_Linux_arm64.tar.gz", using: Gc::GithubPrivateReleaseDownloadStrategy
        sha256 "7e192f92ce2fa7f63b62d8e626af04ba57743bf151e67301a4d445a883dd487c"

        def install
          bin.install "crank"
        end
      end
    end
  end

  test do
    system "#{bin}/crank"
  end
end
