# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/gc/github_private_release_download_strategy"
class Crank < Formula
  desc "GoCardless JSONSchema template generator"
  homepage "https://github.com/gocardless/crank"
  version "7.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gocardless/crank/releases/download/v7.0.0/crank_darwin_amd64", using: Gc::GithubPrivateReleaseDownloadStrategy
      sha256 "c51ed2177cd8a5cfadba07eb292a011290fd6808a66706ced7b3f671580a1f45"

      def install
        bin.install "crank_darwin_amd64" => "crank"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gocardless/crank/releases/download/v7.0.0/crank_darwin_arm64", using: Gc::GithubPrivateReleaseDownloadStrategy
      sha256 "e6afa70fab7bdc612b93cce4b574df47bf884bd5a601f0141daa1fe6321fed83"

      def install
        bin.install "crank_darwin_arm64" => "crank"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gocardless/crank/releases/download/v7.0.0/crank_linux_amd64", using: Gc::GithubPrivateReleaseDownloadStrategy
        sha256 "67c1ef0076629947e0b42d7118a4108c7070bb374f2c9d5934015122fdcbef20"

        def install
          bin.install "crank_linux_amd64" => "crank"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gocardless/crank/releases/download/v7.0.0/crank_linux_arm64", using: Gc::GithubPrivateReleaseDownloadStrategy
        sha256 "d44cf7f057bc0cd942a8eb4ac047ab332837d9a20bd86a5408bc490a8fc762f8"

        def install
          bin.install "crank_linux_arm64" => "crank"
        end
      end
    end
  end

  test do
    system "#{bin}/crank"
  end
end
