# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/gc/github_private_release_download_strategy"
class Devpub < Formula
  desc "A simple utility for working with the pubsub emulator."
  homepage "https://github.com/gocardless/devpub"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gocardless/devpub/releases/download/v0.1.1/devpub_0.1.1_darwin_amd64.tar.gz", using: Gc::GithubPrivateReleaseDownloadStrategy
      sha256 "cebd44280f3ba1e8c51246b0c8024235d2c465d711a4db8d85c687002e5821f9"

      def install
        bin.install "devpub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gocardless/devpub/releases/download/v0.1.1/devpub_0.1.1_darwin_arm64.tar.gz", using: Gc::GithubPrivateReleaseDownloadStrategy
      sha256 "30e040e7842df2cd67699a6c0ee1b8728ad051b46a4cdfca93a03a97d43f865c"

      def install
        bin.install "devpub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/gocardless/devpub/releases/download/v0.1.1/devpub_0.1.1_linux_amd64.tar.gz", using: Gc::GithubPrivateReleaseDownloadStrategy
      sha256 "3d36aaf0470ef6b5004a0c1985c8530f4b1850bbac9e9ced92c6395e4990a35f"
      def install
        bin.install "devpub"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/gocardless/devpub/releases/download/v0.1.1/devpub_0.1.1_linux_arm64.tar.gz", using: Gc::GithubPrivateReleaseDownloadStrategy
      sha256 "a262a560895d6755926785c5d8de78318825cfc61fdf68dfe4f2da0f89456ace"
      def install
        bin.install "devpub"
      end
    end
  end

  test do
    system "#{bin}/devpub version"
  end
end
