# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/gc/github_private_release_download_strategy"
class Devpub < Formula
  desc "A simple utility for working with the pubsub emulator."
  homepage "https://github.com/gocardless/devpub"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gocardless/devpub/releases/download/v0.2.1/devpub_0.2.1_darwin_amd64.tar.gz", using: Gc::GithubPrivateReleaseDownloadStrategy
      sha256 "3ad1cd2e338eb829abca050f69d1bb09f0cfcad1c2534a831bf7bdd4a1a461d9"

      def install
        bin.install "devpub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gocardless/devpub/releases/download/v0.2.1/devpub_0.2.1_darwin_arm64.tar.gz", using: Gc::GithubPrivateReleaseDownloadStrategy
      sha256 "86b74514d62047c3a72367c47b51f18cad43a262c94032ed46f8270b51e7e337"

      def install
        bin.install "devpub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/gocardless/devpub/releases/download/v0.2.1/devpub_0.2.1_linux_amd64.tar.gz", using: Gc::GithubPrivateReleaseDownloadStrategy
      sha256 "f4bce9919ac5010bf0adf9bc64e37bf8fb084edd99e3fd8e541ec0bbea99cfc9"
      def install
        bin.install "devpub"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/gocardless/devpub/releases/download/v0.2.1/devpub_0.2.1_linux_arm64.tar.gz", using: Gc::GithubPrivateReleaseDownloadStrategy
      sha256 "39cd33e6b167daa91bfb80202b8dfd3b8e692f0e8ad9316a71f56407f15f506e"
      def install
        bin.install "devpub"
      end
    end
  end

  test do
    system "#{bin}/devpub version"
  end
end
