# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/gc/github_private_release_download_strategy"
class Dispatcher < Formula
  desc "Continuously dispatching deploys"
  homepage "https://github.com/gocardless/dispatcher"
  version "0.17.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gocardless/dispatcher/releases/download/v0.17.4/dispatcher_0.17.4_darwin_amd64.tar.gz", :using => Gc::GithubPrivateReleaseDownloadStrategy
    sha256 "a99f070180d3bfb79ce7befe466029bc693afc8da454833eb66cc74ff4b7626d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gocardless/dispatcher/releases/download/v0.17.4/dispatcher_0.17.4_linux_amd64.tar.gz", :using => Gc::GithubPrivateReleaseDownloadStrategy
      sha256 "a9219f6ed01e5137344d326519b48a47ad29e83919ce3a897bcab2fd811989b7"
    end
  end

  def install
    bin.install "dispatcher"
  end

  test do
    system "#{bin}/dispatcher version"
  end
end
