# This file was generated by GoReleaser. DO NOT EDIT.
class Draupnir < Formula
  desc "Client for the draupnir database service"
  homepage ""
  version "5.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gocardless/draupnir/releases/download/v5.2.0/draupnir_5.2.0_darwin_amd64.tar.gz"
    sha256 "9753367cabe47b8e61a818d6024553feb01489db5bc249bc2076f21d132bf65b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gocardless/draupnir/releases/download/v5.2.0/draupnir_5.2.0_linux_amd64.tar.gz"
      sha256 "ee2841f95b6cfcb044ef675631f2b85d5aa477c9f14e1c021bc04f0545279ec1"
    end
  end

  def install
    bin.install "draupnir"
  end

  test do
    system "draupnir-client help"
  end
end
