# This file was generated by GoReleaser. DO NOT EDIT.
class Draupnir < Formula
  desc "Client for the draupnir database service"
  homepage ""
  url "https://github.com/gocardless/draupnir/releases/download/v3.0.1/draupnir_3.0.1_darwin_amd64.tar.gz"
  version "3.0.1"
  sha256 "ba81383d2bb9a24e5f95237fcf84966463a1625bd1cca74c37be2a09931cf6db"

  def install
    bin.install "draupnir"
  end

  test do
    system "draupnir-client help"
  end
end
