# This file was generated by GoReleaser. DO NOT EDIT.
class Draupnir < Formula
  desc "Client for the draupnir database service"
  homepage ""
  url "https://github.com/gocardless/draupnir/releases/download/v5.0.1/draupnir_5.0.1_darwin_amd64.tar.gz"
  version "5.0.1"
  sha256 "33783d8d74df66d24bd7d48fa68a82570c88fb9cf42246ceacfc182fa3a00473"

  def install
    bin.install "draupnir"
  end

  test do
    system "draupnir-client help"
  end
end
