# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/gc/github_private_release_download_strategy"
class GcOwners < Formula
  desc "GoCardless code ownership tool"
  homepage "https://github.com/gocardless/gc-owners"
  version "0.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gocardless/codeowners/releases/download/v0.0.9/codeowners_0.0.9_darwin_amd64.tar.gz", :using => Gc::GithubPrivateReleaseDownloadStrategy
    sha256 "4f6113b31e6927ce6e7a20917b0fb32810e026ab0dc325d3a7a425f2de38fe35"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gocardless/codeowners/releases/download/v0.0.9/codeowners_0.0.9_linux_amd64.tar.gz", :using => Gc::GithubPrivateReleaseDownloadStrategy
      sha256 "660c26f7ecbfb19d59dad61f14d95cb0e7c9e317edbd78c58fcbdf93dae435d1"
    end
  end

  def install
    bin.install "gc-owners"
  end

  test do
    system "#{bin}/gc-owners version"
  end
end
