# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/gc/github_private_release_download_strategy"
class GcOwners < Formula
  desc "GoCardless code ownership tool"
  homepage "https://github.com/gocardless/gc-owners"
  version "0.1.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/gocardless/codeowners/releases/download/v0.1.2/codeowners_0.1.2_darwin_amd64.tar.gz", :using => Gc::GithubPrivateReleaseDownloadStrategy
    sha256 "3518ee195faf478c99ea3c08d52a9e42f920e706514889524f9eba4d04b7983a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/gocardless/codeowners/releases/download/v0.1.2/codeowners_0.1.2_linux_amd64.tar.gz", :using => Gc::GithubPrivateReleaseDownloadStrategy
    sha256 "79355f41429a431e09bc87249d490192f2a732a542fde94a3f392caf9e18fb14"
  end

  def install
    bin.install "gc-owners"
  end

  test do
    system "#{bin}/gc-owners version"
  end
end
