# This file was generated by GoReleaser. DO NOT EDIT.
class Pgreplay < Formula
  desc "PostgreSQL load testing tool"
  homepage "https://github.com/gocardless/pgreplay-go"
  url "https://github.com/gocardless/pgreplay-go/releases/download/v0.1.3/pgreplay_0.1.3_darwin_amd64.tar.gz"
  version "0.1.3"
  sha256 "a57794759d3775133278fba5a0e4bedfb609c0c6dcc8857d9876950df0921982"

  def install
    bin.install "pgreplay"
  end

  test do
    system "#{bin}/pgreplay --version"
  end
end
