# This file was generated by GoReleaser. DO NOT EDIT.
class Pgreplay < Formula
  desc "PostgreSQL load testing tool"
  homepage "https://github.com/gocardless/pgreplay-go"
  url "https://github.com/gocardless/pgreplay-go/releases/download/v0.1.1/pgreplay_0.1.1_darwin_amd64.tar.gz"
  version "0.1.1"
  sha256 "12ac3227242610b5926c86a5262ec7ea9b98b47d8fc4ab59ae1a5fed299fb147"

  def install
    bin.install "pgreplay"
  end

  test do
    system "#{bin}/pgreplay version"
  end
end
