# This file was generated by GoReleaser. DO NOT EDIT.
class StolonPgbouncer < Formula
  desc "Stolon add-on for running PgBouncer"
  homepage "https://github.com/gocardless/stolon-pgbouncer"
  url "https://github.com/gocardless/stolon-pgbouncer/releases/download/v0.5.0/stolon-pgbouncer_0.5.0_darwin_amd64.tar.gz"
  version "0.5.0"
  sha256 "90302a5f6c73846fa4bfb530002d9721046124defc5982a7145d869d2e0e977e"

  def install
    bin.install "stolon-pgbouncer"
  end
end
