# This file was generated by GoReleaser. DO NOT EDIT.
class StolonPgbouncer < Formula
  desc "Stolon add-on for running PgBouncer"
  homepage "https://github.com/gocardless/stolon-pgbouncer"
  url "https://github.com/gocardless/stolon-pgbouncer/releases/download/v2.0.1/stolon-pgbouncer_2.0.1_darwin_amd64.tar.gz"
  version "2.0.1"
  sha256 "e199b62b4d13c506007a974db1a79f7e24079c0755612c0a42fd80c45d6ddcf1"

  def install
    bin.install "stolon-pgbouncer"
  end
end
